language: node_js
node_js:
- '8'
cache:
  yarn: true
  directories:
  - node_modules
after_success:
- yarn coverage
deploy:
  provider: npm
  email: toxictoxer@gmail.com
  api_key:
    secure: QgRP2y4mEfwSFUMvhlcLZNHNS3gwIcycZe3lkMNLmMTF/AzMUqQlbqJH9T3EtlAKGJ/PyTRoIo2cF1YUzFe+l+5S8PzRM1JXuskLRz605uopCfcSfRObtPpp4h7UcXdN3sZmMpwZMTe+91vRuKWlxdis+KYp4mCz9tdIk+K9Kw8eSoWg/5nM8Bu+p4P6PcKMZ9iKSMVOnZYMOPT7nfg4n7OSeXMATiJe1exoeQd+MK0LQCFYZSyJWfMP5ENGzCgy21kVPWdPFroGjfTn5sj8Sc7ViwNKBI45EsujthbOHO5WodxcgBYLz2UROxV3Nu4WKCraryocU6om+ly5b6KIoyiXIsjVm1G3P4AAhUA5RnUbYwhjrZFhKvNkdl8I9fAaosj5MozRWQwU4pqlEotLdJR25zgNOWdl1djrsriLKx61adpucVuHrb93Xf4HDII6HIZLWNaAi9fxOQvBtberV/Vhs1fIkEk1Bobb6eCG6YfHvPgSCojP7kYbojiFkxbdXOd2WwfcgK3n0AE4ZZhJnU1qXHADHzB4Gsk/dS5QPmphznWotm5uaqmTB8yGJsM+W/7uG2mQEuh+gVZPFdyYc3wx9nG1FFsRyL+Ocax6gxihR+nZ4l2fmJGmU7xFnhthoTCZMtAD+23QHN4ypAT2hlAWt0F9xDfkitsjBbxlUnE=
  on:
    tags: true
    repo: chinjs/chin-plugin-inkscape
    branch: publish
